[package]
name = "ramdisk"
version = "0.1.0"

edition = "2021"
rust-version = "1.73"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
notify = { version = "6.1.1", features = ["serde"] }
tokio = "1.40.0"
toml = "0.8.19"
